"""Reinciando las migraciones

Revision ID: 38d5ec2f5637
Revises: 
Create Date: 2025-03-16 22:18:35.316738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d5ec2f5637'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('calorias', sa.Integer(), nullable=False),
    sa.Column('inventario', sa.Integer(), nullable=True),
    sa.Column('es_vegetariano', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ingredientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complemento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ingredientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto_ingrediente',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'ingrediente_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_ingrediente')
    op.drop_table('complemento')
    op.drop_table('base')
    op.drop_table('ingredientes')
    # ### end Alembic commands ###
