"""Agregar campo stock a Producto

Revision ID: b9b9dc02ee5b
Revises: c38d22b9855c
Create Date: 2025-03-29 21:27:45.685681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b9dc02ee5b'
down_revision = 'c38d22b9855c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
